### ISSUE TITLE
Line distorted

### ISSUE THREAD

**Issue by colinmeinke** [colinmeinke/wilderness#44]
```
{
  type: 'path',
  d: 'M2 2.078S4.987 4.73 11 4.73s9-2.652 9-2.652',
  strokeWidth: 2,
  strokeLinecap: 'square',
}
```

**Comment by dalisoft** [comment]
I not sure it's bug. Wilderness works fine in every case i've one of morph fan user

**Comment by dalisoft** [comment]
I'm curius, what it's? 
`
{
  type: 'path',
  d: 'M2 2.078S4.987 4.73 11 4.73s9-2.652 9-2.652',
  strokeWidth: 2,
  strokeLinecap: 'square',
}
`

I sure, points (`d` attribute points) isn't works at all

**Comment by colinmeinke** [comment]
```js
{
  type: 'path',
  d: 'M2 2.078S4.987 4.73 11 4.73s9-2.652 9-2.652',
  strokeWidth: 2,
  strokeLinecap: 'square',
} 
```

This shape didn't render correctly?

**Comment by dalisoft** [comment]
Shape d (original) attribute is not correct, shape rendering works fine

**Comment by colinmeinke** [comment]
This issue is because of a bug in svg-points, which has been fixed https://github.com/colinmeinke/svg-points/releases/tag/v3.1.3. Will close when Wilderness dependencies are updated.
