### ISSUE TITLE
Shape moveIndex is limited

### ISSUE THREAD

**Issue by dalisoft** [colinmeinke/wilderness#45]
Demo like we test how it works: http://codepen.io/GreenSock/pen/LpxOqR

But, i tested 50 moveIndex, it's repeats after 6 index (for negative too, but for -5). I can't get correct index

**Comment by colinmeinke** [comment]
Thanks for your report @dalisoft! I'll get back to you next week when I can get some time to look at this 😄

**Comment by dalisoft** [comment]
Thanks

**Comment by dalisoft** [comment]
This tool is free and for any shapes, it morphes better than SnapSVG morphing with more options.
But other way i'm achieving with this is:
1. GSAP morphSVG - Not free and no open-source (best anyway for premium users)
2. `getPointAtLength` method - Even better than GSAP morphSVG, but it's MEMORY hog.

And i'm sure, this is best tool to do morphing, even styling morph is AMAZING. THank you

**Comment by colinmeinke** [comment]
Thanks @dalisoft 😁 

moveIndex works as expected then?

**Comment by dalisoft** [comment]
Yes @colinmeinke. Its works fine, i sure
