### ISSUE TITLE
I can use this in my project?

### ISSUE THREAD

**Issue by dalisoft** [colinmeinke/wilderness#46]
Hi @colinmeinke 
I can use this library to my project (implement, part of it).
And license is like MIT?
Is this free?

**Comment by colinmeinke** [comment]
It's an [ISC license](https://github.com/colinmeinke/wilderness/blob/master/LICENSE.md). From [wikipedia](https://en.wikipedia.org/wiki/ISC_license):

> It is meant to be functionally equivalent to the simplified BSD and the MIT licenses, differing in its removal of language deemed unnecessary following the global adoption of the Berne Convention

Be aware, that I wouldn't say Wilderness is stable yet. Is still under development (as soon as I get some time 😁 ). So use at your own risk. I haven't completed implementing the API, and the API may change. However, I will use semantic versioning as best I can.

**Comment by dalisoft** [comment]
Your js is best ever see in free repos. Thanks for agreeing

**Comment by dalisoft** [comment]
I implement just shapes, normalize and moveIndex
