### ISSUE TITLE
[BUG] "Group" SVG Elements issue

### ISSUE THREAD

**Issue by dalisoft** [colinmeinke/wilderness#47]
Hi.
When you see SVG-Morpheus, they can morph Group elements when group shapes is different. But when i do with Wilderness, it not tweens, fail.
How i can fix it?

Thanks for amazing library and super-secured code :smile:

**Comment by dalisoft** [comment]
As i i'm learned some from clear code writer (@colinmeinke), every path can morphed amazing with bit more code. Thanks

**Comment by colinmeinke** [comment]
Group morphing works as you expect?

**Comment by dalisoft** [comment]
I write bit more code, then works. As your tower demo
