### ISSUE TITLE
Can we improve algorithm for morphing?

### ISSUE THREAD

**Issue by dalisoft** [colinmeinke/wilderness#48]
Hi, i'm very interested in your algorithm as best i know, but some smallest bug i match. Unim.js (my old animation engine, now deprecated) uses SnapSVG algorithm.

Can we improve by mixing both algorithm? Or it's as have we leave?
Thanks for amazing library.

Demo here to see: http://codepen.io/dalisoft/pen/rrPjEd [go-to scroll bottom]

**Comment by colinmeinke** [comment]
Well I'm always open to improving.

Can you be more specific as to what is the exact problem is that could be improved, and how you propose we can improve it?

**Comment by dalisoft** [comment]
You know how to make midpoint and normalize curve, i'm testing (like beta tester) and making demos (more i can't). I'm now looking on `SnapSVG.js`'s `path2curve` function.

**Comment by dalisoft** [comment]
As you see in demo, something like triangulation makes, but `SnapSVG` over-time (higher than `0.67` elapsed) reduced this triangulation

**Comment by dalisoft** [comment]
There need convert `L`, `V`, `H` to `C` for some better morphing looking

**Comment by dalisoft** [comment]
I managed to fix it in my library. I think i soon upload it as PREMIUM
