### ISSUE TITLE
Add auto option to moveIndex

### ISSUE THREAD

**Issue by dalisoft** [colinmeinke/wilderness#49]
Hi @colinmeinke. My last thing to ask, how to there get closest point for both start and end shape?
Like some shapes need `moveIndex: 22`. I want to do it auto for users.
Like `D3js closest point` or `KUTE.js Morph Utility`. Can you give me some instruction or link/guide/tutorial for this?
Thanks. Soon you see new `Wilderness.js like other Morphing` but for `IE9+, Chrome 35+, FF30+, Opera 12.5+`, even bit older browser

**Comment by colinmeinke** [comment]
I don't have any auto for `shapeIndex` at the moment. Would be a cool feature though.

**Comment by dalisoft** [comment]
We need very close to first point from second point.
Like
`[{x:399,y:50,moveTo:true},...], [{x:250,y:70,moveTo:true},{x:390,y:55}]`
and there closest point is `{x:390,y:55}`.
I'm trying to get it

**Comment by dalisoft** [comment]
I almost done. I need performance optimization for animation engine

**Comment by dalisoft** [comment]
I have done this. This can be done via `distance_to_poly` function by @culebron with his amazing answer
Answer on topic: http://gis.stackexchange.com/a/170225

**Comment by dalisoft** [comment]
Hi @colinmeinke 
My project is done: https://github.com/dalisoft/SuperAnimation.js/blob/master/plugins/svgPlugin.js

```html
<svg>.....</svg>
<script src="SuperAnimation.js"></script>
<script src="plugins/domPlugin.js"></script>
<script src="plugins/svgPlugin.js"></script>
```
```javascript
new SuperAnimation('#heart', {
			shapeMorph : {
			shape : '#heart'
			}
		}, {
			shapeMorph : {
			shape : '#star'
			}
		}, {
			duration : 1400,
			easing : 'QuadInOut'
		}).start();
```

**Comment by dalisoft** [comment]
@colinmeinke 
See demo for browsers: https://dalisoft.github.io/SuperAnimation.js/demos/batman.html
Works starting at IE9+, FF3.5+, Opera 12.15+, Chrome.
Performance faster on local, but on server slower. Faster than Wilderness.js anyway and more complex. It's not promoting, just i'm handled `multi-move-to's`.

Thanks to Wilderness.js i maked better morph tool (https://github.com/dalisoft/SuperAnimation.js/blob/master/CREDITS)

**Comment by dalisoft** [comment]
@colinmeinke 

I made small script for this, it works nice, but lighter and faster than http://gis.stackexchange.com/a/170225 solution. 

I don't know ES6 syntax, because syntax maybe wrong, but tried to understandable.
Now finding solution for auto-finding for accurate, fast and better solution.
```javascript
import 'moveIndex' from 'points/moveIndex'

var getCloserIndex = function (a, shape) {

			var index = 0;
			var lat1 = a.x;
			var lon1 = a.y;
			var lat2 = shape[0].x;
			var lon2 = shape[0].y;
			var x1 = lat2 - lat1;
			var x2 = lon2 - lon1;
			var min = Math.sqrt(x1 * x1 + x2 * x2);
			var c = min;

			shape.map(function (v, i) {
				lat2 = v.x;
				lon2 = v.y;

				x1 = lat2 - lat1;
				x2 = lon2 - lon1;
				c = Math.sqrt(x1 * x1 + x2 * x2);

				if (c < min) {
					min = c;
					index = i;
				}
			});
			return index
		}

// a - start shape
// b - end shape
// i - difference between b and a points counts, can be get by (b.length - a.length) before adding midpoint
function moveIndexByClosestPoint(a, b, i) {
			if (a.length < 3 && b.length < 3)
				return [a, b];
			var closestPointA = distance_poly(b[0], a);
			var closestPointB = distance_poly(a[0], b);
			if (closestPointA === closestPointB && closestPointB === 0) {
				return [a, b];
			}
			if (i < 0 && closestPointA === closestPointB) {
				b = moveIndex(b, closestPointB);
			} else if (i > 0) {
				if (closestPointA === closestPointB) {
					b = moveIndex(b, closestPointB);
				} else {
					b = moveIndex(b, closestPointB);
				}
			} else if (i < 0) {
				if (closestPointA < closestPointB) {
					a = moveIndex(a, closestPointA);
				} else if (closestPointA > closestPointB) {
					a = moveIndex(a, closestPointA);
				}
			}
			return [a, b];
		}
```

Thanks again for amazing library

**Comment by dalisoft** [comment]
This can cause unexcepted results

**Comment by colinmeinke** [comment]
This will be optional, so will not be unexpected.

```js
shape({
  type: 'path',
  d: 'M...'
}, {
  type: 'path',
  d: 'M...',
  moveIndex: 'auto'
})
```

**Comment by dalisoft** [comment]
Yes. If you like so i here to help.

**Comment by colinmeinke** [comment]
Moved to https://github.com/colinmeinke/wilderness-core/issues/21
