### ISSUE TITLE
Polyfill Array.from

### ISSUE THREAD

**Issue by colinmeinke** [colinmeinke/wilderness#52]
Because of https://babeljs.io/docs/usage/caveats

Using https://github.com/zloirock/core-js

**Comment by colinmeinke** [comment]
This should just be a warning like https://github.com/serieseight/tinyscroll#browser-support.

**Comment by dalisoft** [comment]
Hi @colinmeinke.
I offer some way, maybe you like it.

I am just made polyfill. You can use ES6 `import` for it as well.

<a href="https://github.com/dalisoft/tez/blob/master/src/shim/array_from.js">Here link</a>

If you see wrong syntax or something, please let me know.

As its my first ES6 work. Inspired from you.

Thanks.
