### ISSUE TITLE
Animation not working in Firefox?

### ISSUE THREAD

**Issue by nearkingdom** [colinmeinke/wilderness#59]
I have been using Wilderness to build a timed animation. See the morphing year countdown on the first screen here: http://tinyurl.com/zne2gr3 

I noticed that it works well in Chrome but doesn't display in Firefox. Is this a known issue? Any ideas what might be happening?

**Comment by colinmeinke** [comment]
Can you provide an isolated example (in codepen) of just the wilderness code that isn't working. The [examples](https://github.com/colinmeinke/wilderness/tree/master/examples) are all working okay in firefox.

**Comment by nearkingdom** [comment]
Ok I have create a CodePen example - and it works fine. The issue must be coming from elsewhere. Thanks for you help.

**Comment by colinmeinke** [comment]
😄 Great. Good luck!
