### ISSUE TITLE
Add rotate shape manipulation

### ISSUE THREAD

**Issue by dalisoft** [colinmeinke/wilderness#60]
Hi. I am using wilderness js and its very amazing. 

As i know scale, translate as offset are supported. I am will be happy if someday you add rotate, skew. 

Transform origin will be very amazing

**Comment by colinmeinke** [comment]
You're right, a `rotate` shape manipulation would be great! It [already exists in points](https://github.com/colinmeinke/points#rotate), so should be easy. As for transform origin, I think this is the same as the existing [`scale` manipulation](https://github.com/colinmeinke/wilderness#shape-manipulation-properties).

**Comment by dalisoft** [comment]
Thanks. Very nice

**Comment by colinmeinke** [comment]
Keeping this open until I have implemented.
