### ISSUE TITLE
Applying matrix to points

### ISSUE THREAD

**Issue by dalisoft** [colinmeinke/wilderness#61]
How to apply mattix transformation to points. Even it line or moveto. I first think of rotate and it worked fine, but first i need skew, second i have problem while parsing transform attribute, so i want do like this.
1. Get transform matrix someway.
2. Apply matrix to points.
3. Flat matrix and remove attribute transform. 

Thanks for very best library. I use it last 3-4month and its works amazing

**Comment by colinmeinke** [comment]
I don't think I understand. Can you provide a very short and simple code example of how that might look in wilderness?

**Comment by dalisoft** [comment]
I provide information. I do demo when have time. 

Applying matrix like rotate to points

**Comment by dalisoft** [comment]
See commented lines for what i want, please http://codepen.io/dalisoft/pen/XpKMpo
Sorry for not real pen (what i need that demo)

**Comment by colinmeinke** [comment]
I don't understand what the output of a `getMatrix` function should be?

```html
<path d="M0,0L10,10" stroke="red" fill="none">
```

```js
const matrix = getMatrix(document.querySelector('path'))

console.log(matrix)

// ?
```

I also don't understand what a matrix manipulation should do?

```js
shape({
  type: 'path',
  d: document.querySelector('path').getAttribute('d'),
  matrix: ['flatten', matrix]
})
```

What would the [points shape](https://github.com/colinmeinke/points) look like for this?

Help me understand!

**Comment by dalisoft** [comment]
https://gist.github.com/timo22345/9413158

This implementation for this js

**Comment by colinmeinke** [comment]
Give me the tl;dr...

**Comment by dalisoft** [comment]
i try.
for users who cannot manipulate transform attribute of svg, especially for "Group" elements this feature is very useful.

* user set matrix as `<g transform="matrix(1, 0, 0, 1, 50, 100)"></g>`
* then gets from `js` matrix as (maybe like this) `matrix = {a:1,b:0,c:0,d:1,e:50,f:100}`
* then user applies this to path. i don't know svg better but i think you understand what i mean. From (`M0,0 L20,30`) to (`M50,100 L70,130`) for `<g>` childrens. This is mean `Flat transform to path` as (https://gist.github.com/timo22345/9413158).
* then remove `transform attribute` from `<g>`

**Comment by colinmeinke** [comment]
I can't see the benefit in this. Manipulations in Wilderness are applied through [manipulation properties on the plain shape object](https://github.com/colinmeinke/wilderness#shape-manipulation-properties).
