### ISSUE TITLE
Update svg-points and points dependencies to fix moveTo issues 

### ISSUE THREAD

**Issue by dalisoft** [colinmeinke/wilderness#62]
How to keep 2-3 moveto in one points list without converting to cubic or line. 

For adding aka normalise points we should keep moveto and not duplicate as possible. 

This also fix much of issue related to animation looks. If you interested test Complex shapes and you see what i mean.

**Comment by colinmeinke** [comment]
Again, not sure what you mean. Can you provide a short and simple code example of your problem.

**Comment by dalisoft** [comment]
I soon give you demo. Or you can test paths has more than 1 moveto

**Comment by dalisoft** [comment]
@colinmeinke Please, checkout http://codepen.io/dalisoft/pen/jyrBOL for how it looks ( unexcepted triangulation ) when `moveTo` is more than one

**Comment by dalisoft** [comment]
latest release really fixes some of multi moveto path with "startshape -1 moveIndex", but not enough it's.
See new demo, http://codepen.io/dalisoft/pen/jyrBOL

**Comment by colinmeinke** [comment]
Just fixed another issue with points that was causing some problems for paths with multiple moveTo points https://github.com/colinmeinke/points/issues/13. Will release a new Wilderness with the fix shortly.

**Comment by dalisoft** [comment]
Thanks. I am too maked some nice things that should apply any transform even matrix. I upload as soon

**Comment by colinmeinke** [comment]
I [just opened an issue](https://github.com/colinmeinke/wilderness/issues/63) that I think addresses the remaining problem with morphing shapes that have multiple `moveTo` points.
