### ISSUE TITLE
DOM decoupling?

### ISSUE THREAD

**Issue by wcandillon** [colinmeinke/wilderness#72]
Is it possible to use this function without the DOM? For instance, I would like to use it in React Native

**Comment by wcandillon** [comment]
https://github.com/colinmeinke/svg-tween seems to be decoupled nicely from the dom. Is it possible to do the same with this library?

**Comment by colinmeinke** [comment]
This repo is the DOM implementation. All the core functionality is at https://github.com/colinmeinke/wilderness-core, which doesn't rely on the DOM. That repo isn't well documented, so you'll probably need to reference this repos src files to work out how to make a similar implementation for react native https://github.com/colinmeinke/wilderness/tree/master/src.

**Comment by wcandillon** [comment]
Awesome thks
